name: Build MkDocs Site

on:
  push:
    branches:
      - main


jobs:
  build-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t mkdocs-docker .

      - name: Build MkDocs site using Docker
        run: |
          mkdir -p site
          docker run --rm -v ${{ github.workspace }}/Mkdocs:/src -v ${{ github.workspace }}/site:/site mkdocs-docker produce

      - name: Upload built site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-site
          path: site/